### ISSUE TITLE
Cannot set property 'method' of undefined

### ISSUE THREAD

**Issue by Citrullin** [avency/coap-cli#73]
### Description

When trying to get a resource, I get the error message:
```
/usr/lib/node_modules/coap-cli/index.js:63
url.method = method
           ^

TypeError: Cannot set property 'method' of undefined
    at Object.<anonymous> (/usr/lib/node_modules/coap-cli/index.js:63:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```
I guess the issue here is the IPv6 address. It's a valid address, but it seems like the code cannot handle it.

### Steps to Reproduce

1. Have a coap server with a IPv6 local address.
2. Try to access this source like `coap get coap://[fe80::fab6:41ff:fe43:b5ab%bt0]/echo`

#### Expected behavior
Success

#### Actual behavior
Error message

### Affected Versions
0.7.1

**Comment by JKRhb** [comment]
I provided a fix for #56 in #125, maybe this issue will be resolved by it as well.

**Comment by gerdemann** [comment]
@Citrullin I published a new version (0.8.0) with @JKRhb changes. Please test it again to see if the problem has been solved.

**Comment by gerdemann** [comment]
Can you try to see if it works with #128?

**Comment by gerdemann** [comment]
Is it also working with the interface in the IPv6 address?
